[[redirects]]
  from = "/spot/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/kbyg/*"
  to = "https://services.surfline.com/kbyg/:splat"
  status = 200

[[redirects]]
  from = "/search/*"
  to = "https://services.surfline.com/search/:splat"
  status = 200

[[redirects]]
  from = "/cdn*"
  to = "https://cams.cdn-surfline.com/cdn:splat"
  status = 200
